name: main

on:
    workflow_dispatch:

jobs:
    build-image:
        name: Build image using swift container plugin
        runs-on: ubuntu-latest
        services:
            registry:
                image: registry:2
                ports:
                    - 5000:5000

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Mark the workspace as safe
              # https://github.com/actions/checkout/issues/766
              run: git config --global --add safe.directory ${GITHUB_WORKSPACE}

            - name: Install the static SDK
              run: |
                  swift sdk install \
                      https://download.swift.org/swift-6.1-release/static-sdk/swift-6.1-RELEASE/swift-6.1-RELEASE_static-linux-0.0.1.artifactbundle.tar.gz \
                      --checksum 111c6f7d280a651208b8c74c0521dd99365d785c1976a6e23162f55f65379ac6

            - name: Build the example
              run: |
                  sed -i'.bak' -e "/swift-container-plugin/ s@(url:.*),@(path: \"$PWD\"),@" Package.swift   # Use plugin from this checkout
                  cat Package.swift
                  swift package \
                      -Xswiftc -warnings-as-errors \
                      --swift-sdk x86_64-swift-linux-musl \
                      --allow-network-connections all \
                      build-container-image \
                      --repository localhost:5000/example \
                      --from scratch
